### ISSUE TITLE
VST3 plugins that do not use JUCE

### ISSUE THREAD

**Issue by dromer** [percussa/ssp-sdk#4]
Maybe the wrong place to ask, but I use a different plugin framework and would like to build plugins for Percussa.

How would I best go about this?

**Comment by bschiett** [comment]
You just use the ssp-sdk, you can use whatever framework you want inside your plugin. You don't need to use JUCE. 
Please join the forum at http://forum.percussa.com/ and post your question there so other developers can chime in.
